name: Build Android/Windows

on:
  workflow_dispatch:
    inputs:
      build-type:
        type: choice
        description: "Artifact Type"
        options:
        - apk
        - appbundle
        - windows
        default: "apk"

jobs:
  build:
    uses: RokctAI/shared-workflows/.github/workflows/universal-flutter-build.yml@main
    with:
      build-type: ${{ inputs.build-type }}
      upload-artifact: true
    secrets: inherit
